2025-08-09 19:29:16,463 | INFO | [LOGGING] Output is being saved to: logs/gpt_prompt_generation_20250809_192916.log
2025-08-09 19:29:16,507 | INFO | Extending pause with 2 new samples starting from index 1
2025-08-09 19:29:16,507 | INFO | Traceback (most recent call last):
  File "/wekafs/ict/pangj/data/speech_tts/hallucinated_sample_generation/generation/gpt_prompt_generation.py", line 267, in <module>
    prompts = extend_ssml_task(args.task, args.n, prompts)
  File "/wekafs/ict/pangj/data/speech_tts/hallucinated_sample_generation/generation/gpt_prompt_generation.py", line 234, in extend_ssml_task
    user_msg = TASK_TEMPLATES[task_name]['user'].format(
KeyError: '\n    "script"'
